services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25032004
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [ backend ]

  rabbitmq:
    image: rabbitmq:4.2-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks: [ backend ]

  logger-service:
    build:
      context: .
      dockerfile: ./logger-service/Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    ports:
      - "8085:8085"
    networks: [ backend ]

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks: [ backend ]

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8083:8083"
    networks: [ backend ]

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8086:8086"
    networks: [ backend ]

  cart-service:
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8082:8082"
    networks: [ backend ]

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    env_file: .env
    depends_on:
      - db
      - rabbitmq
      - logger-service
    ports:
      - "8084:8084"
    networks: [ backend ]

  mailer-service:
    build:
      context: .
      dockerfile: ./mailer-service/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - mailhog
    networks: [ backend ]

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks: [ backend ]

volumes:
  db_data:
  rabbit-data:


networks:
  backend:
