services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25032004
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [ backend ]

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks: [ backend ]

  redis:
    image: redis:8.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: [ backend ]

  logger-service:
    build:
      context: .
      dockerfile: ./logger-service/Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
    ports:
      - "8085:8085"
    networks: [ backend ]

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"
    networks: [ backend ]

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8083:8083"
    networks: [ backend ]

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8086:8086"
    networks: [ backend ]

  cart-service:
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - REDIS_URL=redis:6379
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "8082:8082"
    networks: [ backend ]

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - REDIS_URL=redis:6379
    depends_on:
      - db
      - rabbitmq
      - logger-service
      - redis
    ports:
      - "8084:8084"
    networks: [ backend ]

  mailer-service:
    build:
      context: .
      dockerfile: ./mailer-service/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - mailhog
    networks: [ backend ]

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks: [ backend ]

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks: [ backend ]

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks: [ backend ]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
    networks: [ backend ]

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks: [ backend ]

volumes:
  db_data:
  rabbit-data:
  redis-data:


networks:
  backend:
